on:
  pull_request:
    types: [labeled]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ github.event.label.name }}
      - name: Remove label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --remove-label "${{ github.event.label.name }}"
        env:
          GH_TOKEN: ${{ github.token }}
